name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Install avbtool
        run: |
          git clone https://github.com/avbtool/avbtool.git || {
            echo "Error: Failed to clone avbtool repository"
            exit 1
          }
          sudo cp avbtool/avbtool /usr/local/bin/avbtool || {
            echo "Error: Failed to copy avbtool to bin directory"
            exit 1
          }
          sudo chmod +x /usr/local/bin/avbtool || {
            echo "Error: Failed to set executable permissions"
            exit 1
          }

      - name: Prepare the environment
        run: |
          sudo apt update || {
            echo "Error: Failed to update package list"
            exit 1
          }
          sudo apt install git wget lz4 tar openssl python3 python3-pip -y || {
            echo "Error: Failed to install required packages"
            exit 1
          }
          pip install git+https://github.com/avbtool/avbtool || {
            echo "Error: Failed to install avbtool via pip"
            exit 1
          }

      - name: Fetch image from URL
        run: |
          wget "${GITHUB_EVENT_INPUTS_RECOVERY_URL}" -O recovery.img || {
            echo "Error: Failed to download recovery image"
            exit 1
          }

      - name: Patch Process-1
        run: |
          chmod +x script1.sh magiskboot || {
            echo "Error: Failed to set executable permissions for script1"
            exit 1
          }
          ./script1.sh || {
            echo "Error: Script 1 execution failed"
            exit 1
          }

      - name: Patch Process-2
        run: |
          chmod +x script2.sh || {
            echo "Error: Failed to set executable permissions for script2"
            exit 1
          }
          ./script2.sh || {
            echo "Error: Script 2 execution failed"
            exit 1
          }
          python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin || {
            echo "Error: Failed to extract public key"
            exit 1
          }
          python3 avbtool add_hash_footer \
            --partition_name recovery \
            --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') \
            --image recovery-patched.img \
            --key phh.pem \
            --algorithm SHA256_RSA4096 || {
            echo "Error: Failed to add hash footer"
            exit 1
          }
          mkdir output || {
            echo "Error: Failed to create output directory"
            exit 1
          }
          mv recovery-patched.img output/recovery.img || {
            echo "Error: Failed to move patched recovery image"
            exit 1
          }
          cd output || {
            echo "Error: Failed to change to output directory"
            exit 1
          }
          tar -cvf fastbootd-recovery.tar recovery.img || {
            echo "Error: Failed to create tar archive"
            exit 1
          }
          md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar || {
            echo "Error: Failed to add MD5 checksum"
            exit 1
          }
          mv fastbootd-recovery.tar fastbootd-recovery.tar.md5 || {
            echo "Error: Failed to rename archive with MD5"
            exit 1
          }

      - name: Upload Recovery
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Recovery
          path: output/*.md5
          retention-days: 30
          compression-level: 0
