name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt install git wget lz4 tar openssl python3 python3-pip -y
        pip install git+https://github.com/avbtool/avbtool

    - name: Fetch image from URL
      run: |
        wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img

    - name: Patch Process-1
      run: |
        chmod +x script1.sh magiskboot
        ./script1.sh

    - name: Patch Process-2
      run: |
        chmod +x script2.sh
        ./script2.sh
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') \
          --image recovery-patched.img \
          --key phh.pem \
          --algorithm SHA256_RSA4096

        mkdir output
        mv recovery-patched.img output/recovery.img
        cd output
        tar -cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5

    - name: Upload Recovery
      uses: actions/upload-artifact@v4
      with:
        path: output/*.md5
        name: Patched-Recovery
